title: Custom Bulma Site
description: Can be anything but we never read this variable with {{site.descritption}} so who cares :).
collections:
  docs:
    permalink: "/:collection/:path/"
    output: true
  posts:
    permalink: "/news/:year/:month/:day/:title/"
    output: true
  tutorials:
    output: true
defaults:
  - scope:
      path: _docs
      type: docs
    values:
      layout: docs
  - scope:
      path: _posts
      type: posts
    values:
      layout: news_item
feed:
  categories:
    - release
exclude:
  - ".gitignore"
  - ".jekyll-cache"
  - README.md